### ISSUE TITLE
Update table columns

### ISSUE THREAD

**Issue by monaw** [sinkovit/Spatial-ecology#14]
- [x] lat, then long
- [x] break longitude into 2 columns
- [x] Showing cell sizes 10, 30, 100, 1000
- [x] add area for each animal (square kilometers)
- [x] calculate area from minimum convex polygon
- [ ] file size

**Comment by sinkovit** [comment]
We might still want to make some small tweaks, such as making the column headers more appealing (breaks in right place), but otherwise should be done. The grid dimensions are now calculated for the four choices of pixel sizes, an area column has been added and the first set of columns (min/max lat/long/x/y) have been replaced with min/max easting/northing. Note that we don't want lat/long since not every data set will have that data.

**Comment by monaw** [comment]
Bob will give the file size some more thought...
