### ISSUE TITLE
MCP tab labels and text

### ISSUE THREAD

**Issue by sinkovit** [sinkovit/Spatial-ecology#54]
The MCP tab currently has "Polygon" and "Points" radio buttons. Since the "Polygon" option includes points, we can rename "Polygon and points".

The MCP tab allows multiple animals to be selected and this might not be obvious to all users. Add brief explanatory text somewhere that instructs the user to choose one or more animals.

**Comment by monaw** [comment]
hi @sinkovit - sorry i didn't see this earlier!  i just updated the UI:

![Screenshot 2023-07-26 at 3 48 50 PM](https://github.com/sinkovit/Spatial-ecology/assets/18472048/db83f243-a92f-4ea0-8c50-d88701c477de)

if that is ok, please close this issue, otherwise let me know what changes you'd like, thanks
